name: Release
on:
  push:
    branches: [ master, next, next-major, beta, alpha ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test --if-present
      - name: Build
        run: pnpm build --if-present
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
