name: Release
on:
  push:
    branches: [ master, next, next-major, beta, alpha ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npx -p @antfu/ni nci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test --if-present
      - name: Build
        run: npm run build --if-present
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
